// generatePlan — Generates the FIRST mesocycle of a personalized running training plan.
// Subsequent mesocycles are generated by generateNextMesocycle.

import { onCall, HttpsError } from 'firebase-functions/v2/https';
import { defineSecret } from 'firebase-functions/params';
import { getFirestore, FieldValue } from 'firebase-admin/firestore';

const PROMPT_VERSION = '2025-06-11-v3';
import {
  TrainingZones, PlanDay,
  secToMinStr, estimateZones,
  computePhases, phaseForWeek,
  buildFallbackMesocycle,
  buildDayScheduleHint,
  validateDayCompliance,
  buildStrengthInstructions,
  buildTrailBlock,
} from './planHelpers';

const openAiApiKey = defineSecret('OPENAI_API_KEY');
const openAiModel  = defineSecret('OPENAI_MODEL');

// ═══════════════════════════════════════════════════════════════
// FUNCTION
// ═══════════════════════════════════════════════════════════════

interface RacePayload {
  id?: string;
  name: string;
  date: string;
  distance?: number | string;
}

export const generatePlan = onCall(
  { region: 'europe-west1', cors: true, invoker: 'public', secrets: [openAiApiKey, openAiModel], timeoutSeconds: 300, memory: '512MiB' },
  async (request) => {
    const uid = request.auth?.uid;
    if (!uid) throw new HttpsError('unauthenticated', 'No autenticado');

    const { race, goal, config } = request.data as { race?: RacePayload; goal?: string; config?: Record<string, unknown> };

    if (!race || !goal) throw new HttpsError('invalid-argument', 'Faltan detalles de la carrera o el objetivo.');
    if (!race.date)     throw new HttpsError('invalid-argument', 'La carrera no tiene fecha.');

    const db = getFirestore();

    // E3: verify active subscription server-side before any expensive work
    const callerDoc = await db.collection('users').doc(uid).get();
    const callerData = callerDoc.exists ? callerDoc.data()! : {};
    if (!callerData.is_exempt && callerData.subscription_status !== 'active') {
      throw new HttpsError('permission-denied', 'Necesitas una suscripción activa para generar un plan.');
    }

    // ── Rate limiting: max 5 plan generations per user per 24h ──────────
    // E4: use generation_log (server-only write) so clients cannot bypass the counter.
    const since = new Date(Date.now() - 24 * 60 * 60 * 1000);
    const recentPlans = await db
      .collection('users').doc(uid)
      .collection('generation_log')
      .where('kind', '==', 'plan')
      .where('created_at', '>=', since)
      .count()
      .get();
    if (recentPlans.data().count >= 5) {
      throw new HttpsError('resource-exhausted', 'Límite de generaciones alcanzado. Inténtalo de nuevo en 24 horas.');
    }

    // ── Input validation: prevent oversized/malicious payloads ──────────
    if (typeof goal === 'string' && goal.length > 200) throw new HttpsError('invalid-argument', 'El objetivo es demasiado largo.');
    if (race.name && typeof race.name === 'string' && race.name.length > 150) throw new HttpsError('invalid-argument', 'El nombre de la carrera es demasiado largo.');
    if (config) {
      const rawWeeklyKm    = Number(config.current_weekly_km);
      const rawSessionMin  = Number(config.max_session_minutes);
      const rawElevation   = Number(config.elevation_gain_m);
      const rawDist        = Number(race.distance);
      const rawTargetTime  = Number(config.target_time_seconds);
      const rawInjury      = config.recent_injury_detail;
      const rawRacesCtx    = config.races_context;
      if (!isNaN(rawWeeklyKm)   && rawWeeklyKm   > 300) throw new HttpsError('invalid-argument', 'Distancia semanal fuera de rango.');
      if (!isNaN(rawSessionMin) && rawSessionMin  > 360) throw new HttpsError('invalid-argument', 'Duración de sesión fuera de rango.');
      if (!isNaN(rawElevation)  && rawElevation   > 6000) throw new HttpsError('invalid-argument', 'Desnivel fuera de rango.');
      if (!isNaN(rawDist)       && rawDist        > 320) throw new HttpsError('invalid-argument', 'Distancia de carrera fuera de rango.');
      if (!isNaN(rawTargetTime) && rawTargetTime  > 86400) throw new HttpsError('invalid-argument', 'Tiempo objetivo fuera de rango.');
      if (typeof rawInjury === 'string' && rawInjury.length > 500) throw new HttpsError('invalid-argument', 'Detalle de lesión demasiado largo.');
      if (Array.isArray(rawRacesCtx) && rawRacesCtx.length > 20) throw new HttpsError('invalid-argument', 'Demasiadas carreras en el contexto.');
    }

    const apiKey = openAiApiKey.value();
    if (!apiKey) throw new HttpsError('internal', 'OPENAI_API_KEY no está configurada');
    const model = (openAiModel.value() || 'gpt-4o-mini').trim();

    const raceDate = new Date(race.date);
    if (isNaN(raceDate.getTime())) throw new HttpsError('invalid-argument', 'Fecha de carrera inválida');

    const today     = new Date();
    const startDate = new Date(Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), today.getUTCDate()));
    if (startDate > raceDate) throw new HttpsError('invalid-argument', 'La fecha de la carrera ya pasó o es anterior a hoy');

    const startISO = startDate.toISOString().split('T')[0];
    const raceISO  = raceDate.toISOString().split('T')[0];

    // ── Config ──────────────────────────────────────────────────
    const runDays          = Math.min(Math.max(Number(config?.run_days_per_week) || 4, 2), 7);
    const runDaysOfWeek    = Array.isArray(config?.run_days_of_week)
      ? (config!.run_days_of_week as unknown[]).filter((d): d is number => typeof d === 'number' && d >= 0 && d <= 6)
      : null;
    const includeStrength  = !!config?.include_strength;
    const strengthDaysOfWeek = Array.isArray(config?.strength_days_of_week)
      ? (config!.strength_days_of_week as unknown[]).filter((d): d is number => typeof d === 'number' && d >= 0 && d <= 6)
      : null;
    const strengthDaysCount = includeStrength
      ? Math.min(Math.max(Number(config?.strength_days_per_week) || 1, 1), 3)
      : 0;
    const lastRace    = config?.last_race as { distance_km?: number; time?: string } | undefined;
    const targetTimeSec = Number(config?.target_time_seconds) || null;
    const methodology = ((config?.methodology || 'polarized') as string) as 'polarized' | 'norwegian' | 'classic';
    const distKm      = parseFloat(String(race.distance || '')) || 0;
    const storedZones = config?.stored_zones as { z1_sec_km?: number; z4_sec_km?: number; z5_sec_km?: number } | null;

    // ── Extended runner profile ─────────────────────────────────
    const experienceLevel    = (config?.experience_level as string) || 'intermediate';
    const ageRange           = (config?.age_range as string) || '30-39';
    const currentWeeklyKm    = Number(config?.current_weekly_km) || 40;
    const longestRecentRunKm = Number(config?.longest_recent_run_km) || 15;
    const maxSessionMinutes  = Number(config?.max_session_minutes) || 90;
    const preferredTime      = (config?.preferred_training_time as string) || 'any';
    const hasRecentInjury    = !!config?.has_recent_injury;
    const recentInjuryDetail = (config?.recent_injury_detail as string) || null;
    const injuryAreas        = Array.isArray(config?.injury_areas) ? (config!.injury_areas as string[]) : [];
    const raceTerrain        = (config?.race_terrain as string) || 'road';
    const racePriority       = (config?.race_priority as string) || 'A';
    const elevationGainM     = Number(config?.elevation_gain_m) || 0;
    const mountainDaysOfWeek = Array.isArray(config?.mountain_days_of_week)
      ? (config!.mountain_days_of_week as unknown[]).filter((d): d is number => typeof d === 'number' && d >= 0 && d <= 6)
      : null;
    const roadOnlyDaysOfWeek = Array.isArray(config?.road_only_days_of_week)
      ? (config!.road_only_days_of_week as unknown[]).filter((d): d is number => typeof d === 'number' && d >= 0 && d <= 6)
      : null;
    interface RaceContext { name: string; date: string; distance?: string | null; priority: string; is_target?: boolean; }
    const racesContext = Array.isArray(config?.races_context) ? config.races_context as RaceContext[] : null;

    // ── Zones ───────────────────────────────────────────────────
    let zones: TrainingZones | null = null;
    let targetPace: string | null = null;

    if (targetTimeSec && distKm > 0) {
      zones = estimateZones(targetTimeSec, distKm);
      const pSec = targetTimeSec / distKm;
      targetPace = `${Math.floor(pSec / 60)}:${Math.round(pSec % 60).toString().padStart(2, '0')}/km`;
    } else if (storedZones?.z1_sec_km && storedZones?.z4_sec_km && storedZones?.z5_sec_km) {
      zones = {
        z1:   secToMinStr(storedZones.z1_sec_km),
        z4:   secToMinStr(storedZones.z4_sec_km),
        z5:   secToMinStr(storedZones.z5_sec_km),
        race: secToMinStr(storedZones.z4_sec_km),
      };
    }

    // ── Periodization ───────────────────────────────────────────
    const totalDays  = Math.round((raceDate.getTime() - startDate.getTime()) / 86400000) + 1;
    const totalWeeks = Math.ceil(totalDays / 7);
    const taperWeeks = totalWeeks >= 8 ? 2 : 1;
    const phases     = computePhases(totalWeeks);

    // ── Mesocycle window ────────────────────────────────────────
    // For short plans (≤4 weeks) generate everything in one shot.
    // Otherwise generate only the first 5-week mesocycle.
    const mesoLenWeeks = totalWeeks <= 4 ? totalWeeks : Math.min(
      Math.max(Number(config?.mesocycle_length_weeks) || 5, 3),
      8
    );
    const mesoEndMs  = Math.min(
      startDate.getTime() + mesoLenWeeks * 7 * 86400000- 86400000,
      raceDate.getTime()
    );
    const mesoEndDate = new Date(mesoEndMs);
    const mesoEndISO  = mesoEndDate.toISOString().split('T')[0];
    const totalMesocycles = totalWeeks <= 4 ? 1 : Math.ceil(totalWeeks / mesoLenWeeks);

    const peakLongRun = distKm >= 42 ? '32km' : distKm >= 21 ? '20km' : distKm >= 10 ? '15km' : '12km';

    // ── Prompt ─────────────────────────────────────────────────
    const zonesBlock = zones
      ? `ZONAS DE ENTRENAMIENTO:
  • Z1 Fácil/Aeróbico: ${zones.z1} — conversacional, VT1
  • Z4 Umbral (LT2):   ${zones.z4} — ritmo 10k aprox
  • Z5 VO2max:         ${zones.z5} — ritmo 5k aprox
  • Ritmo objetivo:    ${zones.race}`
      : 'Sin ritmo objetivo. Usar RPE: Z1=5/10, Z4=8/10, Z5=9-10/10.';

    const phasesBlock = phases.map(p =>
      `  • ${p.name.toUpperCase()} (sem ${p.startWeek}→${p.endWeek}): ${p.rule}`
    ).join('\n');

    const methodologyBlock =
      methodology === 'norwegian'
        ? `MÉTODO NORUEGO: 2 sesiones de umbral/sem (martes + jueves), todo lo demás Z1 estricto.`
        : methodology === 'classic'
        ? `PERIODIZACIÓN CLÁSICA: Series martes (Z5) · Tempo jueves (Z4) · Largo domingo (Z1).`
        : `MÉTODO POLARIZADO (Seiler): 80% vol Z1 puro, 20% en Z4-Z5. Máx 2 sesiones calidad/sem, nunca consecutivas.`;

    // ── Runner profile block ─────────────────────────────────────
    const expLabel = experienceLevel === 'beginner' ? 'Principiante (<1 año)' :
                     experienceLevel === 'intermediate' ? 'Intermedio (1-3 años)' :
                     experienceLevel === 'advanced' ? 'Avanzado (3+ años)' : 'Élite/Sub-élite';
    const isTrailRace  = raceTerrain === 'trail' || raceTerrain === 'mixed';
    const terrainLabel = raceTerrain === 'road'  ? 'asfalto/ciudad' :
                         raceTerrain === 'trail' ? `trail/montaña${elevationGainM > 0 ? ` · ${elevationGainM}D+` : ''}` :
                         raceTerrain === 'mixed' ? `mixto asfalto+trail${elevationGainM > 0 ? ` · ${elevationGainM}D+` : ''}` : 'pista atletismo';
    const priorityLabel = racePriority === 'A' ? 'Carrera A — objetivo principal, taper completo' :
                          racePriority === 'B' ? 'Carrera B — objetivo secundario, taper parcial 3-4 días' :
                          'Carrera C — entrenamiento con dorsales, sin taper';
    const injuryBlock = (() => {
      const parts: string[] = [];
      if (hasRecentInjury) parts.push(`LESIÓN RECIENTE: "${recentInjuryDetail || 'sí, sin detalles'}" — carga inicial conservadora, sin series hasta semana 2`);
      const areas = injuryAreas.filter(a => a !== 'Sin lesiones conocidas');
      if (areas.length > 0) parts.push(`Zonas crónicas: ${areas.join(', ')} — incluir ejercicios preventivos específicos y evitar sobrecargar esas zonas`);
      return parts.length > 0 ? parts.join('\n  ') : 'Sin lesiones ni limitaciones';
    })();

    const runnerProfileBlock = `PERFIL DEL CORREDOR:
  • Nivel: ${expLabel}
  • Edad: ${ageRange} años
  • Volumen actual: ~${currentWeeklyKm} km/semana
  • Rodaje largo reciente: ~${longestRecentRunKm} km
  • Tiempo máximo/sesión: ${maxSessionMinutes} min — NO superar este límite en ninguna sesión
  • Momento preferido: ${preferredTime === 'morning' ? 'mañana' : preferredTime === 'afternoon' ? 'tarde' : preferredTime === 'evening' ? 'noche' : 'flexible'}
  • Terreno objetivo: ${terrainLabel}
  • Prioridad carrera: ${priorityLabel}
  • Lesiones: ${injuryBlock}`;

    // ── Progression constraints derived from profile ────────────
    const maxInitialLongRunKm  = Math.min(longestRecentRunKm + 2, longestRecentRunKm * 1.1);
    const maxWeeklyKmFirstWeek = Math.round(currentWeeklyKm * (experienceLevel === 'beginner' ? 0.85 : 1.0));
    const maxSessionNote = `Ninguna sesión supere ${maxSessionMinutes} minutos — ritmo de rodaje ajustado a este límite.`;

    const DAY_NAMES_ES = ['dom', 'lun', 'mar', 'mié', 'jue', 'vie', 'sáb'];
    const strengthNote = includeStrength
      ? strengthDaysOfWeek && strengthDaysOfWeek.length > 0
        ? `Fuerza FIJA los: ${strengthDaysOfWeek.map(d => DAY_NAMES_ES[d]).join(', ')} — NO poner fuerza en otros días.`
        : `Fuerza: ${strengthDaysCount} sesión/es semana (días libres).`
      : 'Sin fuerza.';

    const scheduleHint = buildDayScheduleHint(
      startISO, mesoEndISO,
      runDaysOfWeek && runDaysOfWeek.length > 0 ? runDaysOfWeek : null,
      strengthDaysOfWeek && strengthDaysOfWeek.length > 0 ? strengthDaysOfWeek : null,
    );

    const strengthBlock = includeStrength ? buildStrengthInstructions({
      strengthDaysCount,
      distKm,
      experienceLevel,
      terrain: raceTerrain,
      hasRecentInjury,
      injuryDetail:  recentInjuryDetail,
      injuryAreas,
    }) : '';

    // ── Race calendar block ─────────────────────────────────────
    const racesCalendarBlock = racesContext && racesContext.length > 1
      ? `CALENDARIO DE OBJETIVOS (${racesContext.length} carreras próximas):
${racesContext.map(r => {
  const marker = r.is_target ? ' ← CARRERA OBJETIVO (este mesociclo)' : '';
  const priLabel = r.priority === 'A' ? 'Prioridad A — taper completo' : r.priority === 'B' ? 'Prioridad B — taper parcial (3-4 días)' : 'Prioridad C — sin taper';
  return `  • ${r.name} · ${r.date}${r.distance ? ' · ' + r.distance : ''} · ${priLabel}${marker}`;
}).join('\n')}
Planifica la carga, las semanas de descarga y los tapers de acuerdo con estas prioridades. Las carreras B y C NO interrumpen el bloque de carga salvo el taper indicado.`
      : '';

    const developerInstructions = `Eres un entrenador de running científico y especializado. Devuelve SOLO JSON válido, sin texto antes o después. [v:${PROMPT_VERSION}]

FORMATO (running/descanso):
{"plan":[{"date":"YYYY-MM-DD","description":"descripción ejecutable","explanation":{"type":"series|umbral|tempo|largo|suave|subida|descanso","purpose":"objetivo fisiológico","details":"instrucciones paso a paso","intensity":"zona/ritmo/RPE o null","elevation_gain_m":null,"phase":"base|desarrollo|especifico|taper"}}]}
TRAIL — cuando type==="subida": pon elevation_gain_m con los metros de desnivel de la sesión (ej: 500). Exprésalo en la description como "Xmin/YD+" o "Xkm/YD+".

FORMATO (fuerza — usa SIEMPRE este cuando type==="fuerza"):
{"plan":[{"date":"YYYY-MM-DD","description":"descripción breve","explanation":{"type":"fuerza","purpose":"objetivo fisiológico","exercises":[{"sets":3,"reps":"10","name":"Nombre ejercicio","notes":"ritmo excéntrico, descanso u obs. breve — opcional"}],"details":"instrucciones generales de la sesión (calentamiento, orden, descansos entre series)","intensity":null,"elevation_gain_m":null,"phase":"base|desarrollo|especifico|taper"}}]}
REGLAS FUERZA:
- exercises debe listar TODOS los ejercicios, uno por objeto. Mínimo 4 ejercicios por sesión.
- "reps" puede ser "10", "10-12", "30s" o "1 min".
- NUNCA agrupes ejercicios en bloques como un solo elemento. Cada ejercicio va en su propio objeto.
- INCORRECTO: {"name":"BLOQUE A: Sentadilla + Hip thrust","sets":3,"reps":"10"}
- CORRECTO: {"name":"Sentadilla búlgara","sets":3,"reps":"10"}, {"name":"Hip thrust","sets":3,"reps":"12"}
- Si la sesión tiene bloques (A, B, C), indica el bloque en el campo "notes" del ejercicio, no en "name".

PLAN COMPLETO (contexto): ${race.name} · ${distKm || '?'}km · ${raceISO} · ${totalWeeks} semanas totales
MESOCICLO A GENERAR: 1 de ${totalMesocycles} — SOLO desde ${startISO} hasta ${mesoEndISO} (${mesoLenWeeks} semanas)
${runDaysOfWeek && runDaysOfWeek.length > 0
  ? `Running FIJO los: ${runDaysOfWeek.map(d => DAY_NAMES_ES[d]).join(', ')}`
  : `Días running/sem: ${runDays}`} · ${strengthNote}
Objetivo corredor: ${goal} · Ritmo objetivo: ${targetPace || 'no definido'}
Marca previa: ${lastRace?.distance_km ? `${lastRace.distance_km}km en ${lastRace.time || '?'}` : 'no disponible'}

${runnerProfileBlock}
${racesCalendarBlock ? `\n${racesCalendarBlock}\n` : ''}
RESTRICCIONES DE CARGA INICIALES:
• Semana 1 máx ~${maxWeeklyKmFirstWeek} km totales (no superar volumen actual de golpe)
• Rodaje largo semana 1 máx ~${Math.round(maxInitialLongRunKm)} km
• ${maxSessionNote}
${hasRecentInjury ? '• LESIÓN RECIENTE: primera semana sin series ni calidad — solo rodajes suaves y fuerza preventiva' : ''}
${raceTerrain === 'track' ? '• PISTA: mayor énfasis en series de velocidad y trabajo a ritmo de carrera' : ''}
${isTrailRace ? buildTrailBlock(elevationGainM, distKm) : ''}
${racePriority === 'C' ? '• CARRERA C: no hay taper — última semana igual que las anteriores, sin reducción de carga' : ''}
${(mountainDaysOfWeek && mountainDaysOfWeek.length > 0) || (roadOnlyDaysOfWeek && roadOnlyDaysOfWeek.length > 0) ? `RESTRICCIÓN DE SUPERFICIE (OBLIGATORIO — incumplir invalida el plan):
${mountainDaysOfWeek && mountainDaysOfWeek.length > 0 ? `• MONTAÑA/TRAIL (desnivel, terreno técnico, series en monte): ÚNICAMENTE los ${mountainDaysOfWeek.map((d: number) => DAY_NAMES_ES[d]).join(', ')}. Fuera de estos días NO asignes sesiones de montaña ni trail.` : ''}
${roadOnlyDaysOfWeek && roadOnlyDaysOfWeek.length > 0 ? `• SOLO ASFALTO (rodajes llanos, series en carretera o pista): ÚNICAMENTE los ${roadOnlyDaysOfWeek.map((d: number) => DAY_NAMES_ES[d]).join(', ')}. En estos días el corredor no puede acceder a montaña.` : ''}
El corredor tiene esta restricción logística real — respétala siempre, también en semanas de calidad y en las semanas de carga máxima.` : ''}

${zonesBlock}

FASES DEL PLAN COMPLETO:
${phasesBlock}

${methodologyBlock}
${strengthBlock ? `\n${strengthBlock}\n` : ''}${scheduleHint ? `
CALENDARIO OBLIGATORIO — sigue EXACTAMENTE esta estructura por fecha:
${scheduleHint}
Los días marcados RUNNING deben tener workout de carrera (suave, calidad o largo).
Los días marcados FUERZA deben tener sesión de fuerza running-specific.
Los días marcados Descanso deben ser descanso. NO cambies ningún día.` : ''}
REGLAS (incumplir invalida el plan):
1. Descarga cada 4ª semana (−25-30% volumen)
2. Máx ${peakLongRun} en rodaje largo
3. Sin sesiones calidad en días consecutivos (48h mínimo entre ellas)
4. Fase BASE: cero calidad, 100% Z1
5. Rodajes suaves SIEMPRE en Z1
6. Adaptar complejidad de las sesiones al nivel ${expLabel}
7. Respetar el tiempo máximo de sesión de ${maxSessionMinutes} min
8. EXACTAMENTE ${runDays} sesión/es de running por semana — ni una más, ni una menos. El resto de días son descanso${includeStrength ? ' o fuerza' : ''}.
${distKm >= 15 ? `9. Una sesión por semana DEBE tener type="largo" (el rodaje más largo de esa semana). No llamarla "suave" aunque sea en Z1. El largo es obligatorio cada semana sin excepción.` : ''}
Genera EXACTAMENTE las fechas de ${startISO} a ${mesoEndISO}. Nada más.`;

    const userPrompt = `Genera el mesociclo 1 (${startISO} → ${mesoEndISO}) del plan para ${race.name}.`;

    // ── OpenAI call ─────────────────────────────────────────────
    async function callResponsesAPI(activeModel: string): Promise<{ text: string; inputTokens: number; outputTokens: number }> {
      const res = await fetch('https://api.openai.com/v1/responses', {
        method: 'POST',
        headers: { Authorization: `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({
          model:             activeModel,
          max_output_tokens: 16384,
          text:              { format: { type: 'json_object' } },
          input: [
            { role: 'developer', content: developerInstructions },
            { role: 'user',      content: userPrompt },
          ],
        }),
        signal: AbortSignal.timeout(120_000),
      });
      const raw = await res.text();
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      let data: any = null;
      try { data = JSON.parse(raw); } catch { /* keep raw */ }
      if (!res.ok) throw new Error(data?.error?.message || `OpenAI error ${res.status}`);

      const outputs: string[] = [];
      if (Array.isArray(data?.output)) {
        for (const item of data.output) {
          if (item?.content && Array.isArray(item.content)) {
            for (const c of item.content) {
              if (c.type === 'output_text' && typeof c.text === 'string') outputs.push(c.text);
            }
          }
        }
      }
      const combined = outputs.join('\n').trim();
      if (!combined) throw new Error('Respuesta OpenAI vacía');
      return {
        text: combined,
        inputTokens:  data?.usage?.input_tokens  || 0,
        outputTokens: data?.usage?.output_tokens || 0,
      };
    }

    // Type classifier for fallback
    function classify(desc: string): string {
      const d = desc.toLowerCase();
      if (d.includes('series') || d.includes('fartlek') || /\dx\d/.test(d) || /\d×\d/.test(d)) return 'series';
      if (d.includes('umbral')) return 'umbral';
      if (d.includes('tempo'))  return 'tempo';
      if (d.includes('largo'))  return 'largo';
      if (d.includes('descanso') || d.includes('rest')) return 'descanso';
      if (d.includes('fuerza')) return 'fuerza';
      return 'suave';
    }

    // ── Try OpenAI, fall back to algorithmic ───────────────────
    let rawContent: string | null = null;
    let openAiError: string | null = null;
    let usedModel: string | null = null;
    let inputTokens = 0, outputTokens = 0;
    const candidateModels = [model, 'gpt-4o-mini'];

    for (const m of candidateModels) {
      try {
        const r   = await callResponsesAPI(m);
        rawContent    = r.text;
        inputTokens   = r.inputTokens;
        outputTokens  = r.outputTokens;
        usedModel     = m;
        break;
      } catch (err) {
        openAiError = (err as Error).message;
      }
    }

    let parsedPlan: { plan: PlanDay[] } | null = null;
    if (rawContent) {
      const first = rawContent.indexOf('{');
      const last  = rawContent.lastIndexOf('}');
      if (first !== -1 && last !== -1 && last > first) {
        try { parsedPlan = JSON.parse(rawContent.slice(first, last + 1).trim()); }
        catch { /* ignore */ }
      }
    }

    // Validate AI respected specific day constraints; force fallback if not
    if (parsedPlan?.plan && Array.isArray(parsedPlan.plan)) {
      const aiOk = validateDayCompliance(
        parsedPlan.plan,
        runDaysOfWeek && runDaysOfWeek.length > 0 ? runDaysOfWeek : null,
        strengthDaysOfWeek && strengthDaysOfWeek.length > 0 ? strengthDaysOfWeek : null,
        runDays,
      );
      if (!aiOk) { parsedPlan = null; usedModel = null; }
    }

    if (!parsedPlan || !parsedPlan.plan || !Array.isArray(parsedPlan.plan)) {
      parsedPlan = buildFallbackMesocycle({
        startISO,
        endISO:              mesoEndISO,
        totalWeeks,
        mesocycleStartWeek:  1,
        phases,
        taperWeeks,
        runDays,
        runDaysOfWeek:       runDaysOfWeek && runDaysOfWeek.length > 0 ? runDaysOfWeek : null,
        includeStrength,
        strengthDaysOfWeek:  strengthDaysOfWeek ?? null,
        strengthDaysCount,
        distKm,
        methodology,
        zones,
      });
      if (!usedModel) usedModel = `fallback-${methodology}`;
    }

    // Validate + fill missing explanations
    parsedPlan.plan.forEach(d => {
      if (!/^\d{4}-\d{2}-\d{2}$/.test(d.date))     throw new HttpsError('internal', `Fecha inválida: ${d.date}`);
      if (typeof d.description !== 'string')          throw new HttpsError('internal', 'Descripción inválida');
      if (!d.explanation || typeof d.explanation !== 'object') {
        const type = classify(d.description);
        d.explanation = { type, purpose: 'Entrenamiento', details: d.description };
      }
    });

    // Log successful generation (rate limiting + analytics)
    try {
      await db.collection('users').doc(uid).collection('generation_log').add({
        kind:           'plan',
        model:          usedModel,
        prompt_version: PROMPT_VERSION,
        input_tokens:   inputTokens,
        output_tokens:  outputTokens,
        created_at:     new Date(),
      });
    } catch { /* non-critical */ }

    // ── Sprint 2: optional server-side persistence ─────────────
    // When config.persist_server_side is true, the server writes plan doc + workouts
    // to Firestore so the client only needs to do the version snapshot.
    const persistServerSide = !!config?.persist_server_side;
    const persistPlanId     = (config?.plan_id as string | undefined) || null;

    if (persistServerSide) {
      const planDocId  = persistPlanId || db.collection('users').doc(uid).collection('training_plans').doc().id;
      const planRef    = db.collection('users').doc(uid).collection('training_plans').doc(planDocId);

      // Delete existing workouts for this plan (idempotency)
      if (persistPlanId) {
        const oldWorkoutsSnap = await db.collection('users').doc(uid).collection('workouts')
          .where('plan_id', '==', persistPlanId).get();
        if (!oldWorkoutsSnap.empty) {
          const delBatch = db.batch();
          oldWorkoutsSnap.docs.forEach(d => delBatch.delete(d.ref));
          await delBatch.commit();
        }
      }

      // Write plan document
      const raceId = (race as any).id as string | undefined;
      await planRef.set({
        primary_race_id:        raceId || null,
        race_id:                raceId || null,
        goal,
        model:                  usedModel || null,
        used_fallback:          !rawContent || (usedModel?.startsWith('fallback') ?? false),
        openai_error:           openAiError || null,
        run_days_per_week:      runDays,
        run_days_of_week:       runDaysOfWeek && runDaysOfWeek.length > 0 ? runDaysOfWeek : null,
        include_strength:       includeStrength,
        strength_days_of_week:  includeStrength && strengthDaysOfWeek && strengthDaysOfWeek.length > 0 ? strengthDaysOfWeek : null,
        strength_days_per_week: includeStrength ? strengthDaysCount : null,
        mountain_days_of_week:  mountainDaysOfWeek && mountainDaysOfWeek.length > 0 ? mountainDaysOfWeek : null,
        road_only_days_of_week: roadOnlyDaysOfWeek && roadOnlyDaysOfWeek.length > 0 ? roadOnlyDaysOfWeek : null,
        last_race_distance_km:  (config?.last_race as any)?.distance_km || null,
        last_race_time_sec:     (config?.last_race as any)?.time_seconds || null,
        target_race_time_sec:   targetTimeSec,
        methodology,
        race_terrain:           raceTerrain,
        elevation_gain_m:       Number(config?.elevation_gain_m) || null,
        experience_level:       experienceLevel,
        age_range:              ageRange,
        current_weekly_km:      currentWeeklyKm,
        longest_recent_run_km:  longestRecentRunKm,
        max_session_minutes:    maxSessionMinutes,
        preferred_training_time: preferredTime,
        has_recent_injury:      hasRecentInjury,
        recent_injury_detail:   recentInjuryDetail || null,
        injury_areas:           injuryAreas,
        total_weeks:            totalWeeks,
        total_mesocycles:       totalMesocycles,
        mesocycle_number:       1,
        mesocycle_length_weeks: mesoLenWeeks,
        plan_start_date:        startISO,
        mesocycle_start_date:   startISO,
        mesocycle_end_date:     mesoEndISO,
        created_at:             FieldValue.serverTimestamp(),
      });

      // Batch write workouts
      const distRegex = /(\d+(?:[.,]\d+)?)\s?(?:km|k)\b/i;
      const durRegex  = /(\d{1,3})\s?(?:min|mins)\b/i;
      const wBatch = db.batch();
      for (const w of parsedPlan.plan) {
        if (!/^\d{4}-\d{2}-\d{2}$/.test(w.date)) continue;
        const desc   = w.description || '';
        const dMatch = desc.match(distRegex);
        const tMatch = desc.match(durRegex);
        const wRef   = db.collection('users').doc(uid).collection('workouts').doc();
        wBatch.set(wRef, {
          plan_id:          planDocId,
          workout_date:     w.date,
          description:      desc,
          type:             (w.explanation as any)?.type ?? null,
          distance_km:      dMatch ? parseFloat(dMatch[1].replace(',', '.')) : null,
          duration_min:     tMatch ? parseInt(tMatch[1], 10) : null,
          elevation_gain_m: (w.explanation as any)?.elevation_gain_m ?? null,
          explanation_json: w.explanation || null,
          is_completed:     false,
          created_at:       FieldValue.serverTimestamp(),
        });
      }
      await wBatch.commit();

      return {
        ...parsedPlan,
        meta: {
          fallback:               !rawContent || usedModel?.startsWith('fallback'),
          openAiError,
          model:                  usedModel,
          methodology,
          zones,
          phases:                 phases.map(p => ({ name: p.name, startWeek: p.startWeek, endWeek: p.endWeek })),
          total_weeks:            totalWeeks,
          mesocycle_number:       1,
          mesocycle_length_weeks: mesoLenWeeks,
          plan_start_date:        startISO,
          mesocycle_start_date:   startISO,
          mesocycle_end_date:     mesoEndISO,
          total_mesocycles:       totalMesocycles,
          server_persisted:       true,
          plan_id:                planDocId,
        },
      };
    }

    return {
      ...parsedPlan,
      meta: {
        fallback:               !rawContent || usedModel?.startsWith('fallback'),
        openAiError,
        model:                  usedModel,
        methodology,
        zones,
        phases:                 phases.map(p => ({ name: p.name, startWeek: p.startWeek, endWeek: p.endWeek })),
        total_weeks:            totalWeeks,
        mesocycle_number:       1,
        mesocycle_length_weeks: mesoLenWeeks,
        plan_start_date:        startISO,   // E1: immutable, never overwritten
        mesocycle_start_date:   startISO,
        mesocycle_end_date:     mesoEndISO,
        total_mesocycles:       totalMesocycles,
        server_persisted:       false,
      },
    };
  }
);

