"use strict";
// generatePlan — Generates the FIRST mesocycle of a personalized running training plan.
// Subsequent mesocycles are generated by generateNextMesocycle.
Object.defineProperty(exports, "__esModule", { value: true });
exports.generatePlan = void 0;
const https_1 = require("firebase-functions/v2/https");
const params_1 = require("firebase-functions/params");
const planHelpers_1 = require("./planHelpers");
const openAiApiKey = (0, params_1.defineSecret)('OPENAI_API_KEY');
const openAiModel = (0, params_1.defineSecret)('OPENAI_MODEL');
exports.generatePlan = (0, https_1.onCall)({ region: 'europe-west1', cors: true, invoker: 'public', secrets: [openAiApiKey, openAiModel], timeoutSeconds: 300, memory: '512MiB' }, async (request) => {
    var _a;
    const uid = (_a = request.auth) === null || _a === void 0 ? void 0 : _a.uid;
    if (!uid)
        throw new https_1.HttpsError('unauthenticated', 'No autenticado');
    const { race, goal, config } = request.data;
    if (!race || !goal)
        throw new https_1.HttpsError('invalid-argument', 'Faltan detalles de la carrera o el objetivo.');
    if (!race.date)
        throw new https_1.HttpsError('invalid-argument', 'La carrera no tiene fecha.');
    const apiKey = openAiApiKey.value();
    if (!apiKey)
        throw new https_1.HttpsError('internal', 'OPENAI_API_KEY no está configurada');
    const model = openAiModel.value() || 'gpt-4o-mini';
    const raceDate = new Date(race.date);
    if (isNaN(raceDate.getTime()))
        throw new https_1.HttpsError('invalid-argument', 'Fecha de carrera inválida');
    const today = new Date();
    const startDate = new Date(Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), today.getUTCDate()));
    if (startDate > raceDate)
        throw new https_1.HttpsError('invalid-argument', 'La fecha de la carrera ya pasó o es anterior a hoy');
    const startISO = startDate.toISOString().split('T')[0];
    const raceISO = raceDate.toISOString().split('T')[0];
    // ── Config ──────────────────────────────────────────────────
    const runDays = Math.min(Math.max(Number(config === null || config === void 0 ? void 0 : config.run_days_per_week) || 4, 2), 7);
    const runDaysOfWeek = Array.isArray(config === null || config === void 0 ? void 0 : config.run_days_of_week)
        ? config.run_days_of_week.filter((d) => typeof d === 'number' && d >= 0 && d <= 6)
        : null;
    const includeStrength = !!(config === null || config === void 0 ? void 0 : config.include_strength);
    const strengthDaysOfWeek = Array.isArray(config === null || config === void 0 ? void 0 : config.strength_days_of_week)
        ? config.strength_days_of_week.filter((d) => typeof d === 'number' && d >= 0 && d <= 6)
        : null;
    const strengthDaysCount = includeStrength
        ? Math.min(Math.max(Number(config === null || config === void 0 ? void 0 : config.strength_days_per_week) || 1, 1), 3)
        : 0;
    const lastRace = config === null || config === void 0 ? void 0 : config.last_race;
    const targetTimeSec = Number(config === null || config === void 0 ? void 0 : config.target_time_seconds) || null;
    const methodology = ((config === null || config === void 0 ? void 0 : config.methodology) || 'polarized');
    const distKm = Number(race.distance) || 0;
    const storedZones = config === null || config === void 0 ? void 0 : config.stored_zones;
    // ── Extended runner profile ─────────────────────────────────
    const experienceLevel = (config === null || config === void 0 ? void 0 : config.experience_level) || 'intermediate';
    const ageRange = (config === null || config === void 0 ? void 0 : config.age_range) || '30-39';
    const currentWeeklyKm = Number(config === null || config === void 0 ? void 0 : config.current_weekly_km) || 40;
    const longestRecentRunKm = Number(config === null || config === void 0 ? void 0 : config.longest_recent_run_km) || 15;
    const maxSessionMinutes = Number(config === null || config === void 0 ? void 0 : config.max_session_minutes) || 90;
    const preferredTime = (config === null || config === void 0 ? void 0 : config.preferred_training_time) || 'any';
    const hasRecentInjury = !!(config === null || config === void 0 ? void 0 : config.has_recent_injury);
    const recentInjuryDetail = (config === null || config === void 0 ? void 0 : config.recent_injury_detail) || null;
    const injuryAreas = Array.isArray(config === null || config === void 0 ? void 0 : config.injury_areas) ? config.injury_areas : [];
    const raceTerrain = (config === null || config === void 0 ? void 0 : config.race_terrain) || 'road';
    const racePriority = (config === null || config === void 0 ? void 0 : config.race_priority) || 'A';
    // ── Zones ───────────────────────────────────────────────────
    let zones = null;
    let targetPace = null;
    if (targetTimeSec && distKm > 0) {
        zones = (0, planHelpers_1.estimateZones)(targetTimeSec, distKm);
        const pSec = targetTimeSec / distKm;
        targetPace = `${Math.floor(pSec / 60)}:${Math.round(pSec % 60).toString().padStart(2, '0')}/km`;
    }
    else if ((storedZones === null || storedZones === void 0 ? void 0 : storedZones.z1_sec_km) && (storedZones === null || storedZones === void 0 ? void 0 : storedZones.z4_sec_km) && (storedZones === null || storedZones === void 0 ? void 0 : storedZones.z5_sec_km)) {
        zones = {
            z1: (0, planHelpers_1.secToMinStr)(storedZones.z1_sec_km),
            z4: (0, planHelpers_1.secToMinStr)(storedZones.z4_sec_km),
            z5: (0, planHelpers_1.secToMinStr)(storedZones.z5_sec_km),
            race: (0, planHelpers_1.secToMinStr)(storedZones.z4_sec_km),
        };
    }
    // ── Periodization ───────────────────────────────────────────
    const totalDays = Math.round((raceDate.getTime() - startDate.getTime()) / 86400000) + 1;
    const totalWeeks = Math.ceil(totalDays / 7);
    const taperWeeks = totalWeeks >= 8 ? 2 : 1;
    const phases = (0, planHelpers_1.computePhases)(totalWeeks);
    // ── Mesocycle window ────────────────────────────────────────
    // For short plans (≤4 weeks) generate everything in one shot.
    // Otherwise generate only the first 5-week mesocycle.
    const mesoLenWeeks = totalWeeks <= 4 ? totalWeeks : Math.min(Math.max(Number(config === null || config === void 0 ? void 0 : config.mesocycle_length_weeks) || 5, 3), 8);
    const mesoEndMs = Math.min(startDate.getTime() + mesoLenWeeks * 7 * 86400000 - 86400000, raceDate.getTime());
    const mesoEndDate = new Date(mesoEndMs);
    const mesoEndISO = mesoEndDate.toISOString().split('T')[0];
    const totalMesocycles = totalWeeks <= 4 ? 1 : Math.ceil(totalWeeks / mesoLenWeeks);
    const peakLongRun = distKm >= 42 ? '32km' : distKm >= 21 ? '20km' : distKm >= 10 ? '15km' : '12km';
    // ── Prompt ─────────────────────────────────────────────────
    const zonesBlock = zones
        ? `ZONAS DE ENTRENAMIENTO:
  • Z1 Fácil/Aeróbico: ${zones.z1} — conversacional, VT1
  • Z4 Umbral (LT2):   ${zones.z4} — ritmo 10k aprox
  • Z5 VO2max:         ${zones.z5} — ritmo 5k aprox
  • Ritmo objetivo:    ${zones.race}`
        : 'Sin ritmo objetivo. Usar RPE: Z1=5/10, Z4=8/10, Z5=9-10/10.';
    const phasesBlock = phases.map(p => `  • ${p.name.toUpperCase()} (sem ${p.startWeek}→${p.endWeek}): ${p.rule}`).join('\n');
    const methodologyBlock = methodology === 'norwegian'
        ? `MÉTODO NORUEGO: 2 sesiones de umbral/sem (martes + jueves), todo lo demás Z1 estricto.`
        : methodology === 'classic'
            ? `PERIODIZACIÓN CLÁSICA: Series martes (Z5) · Tempo jueves (Z4) · Largo domingo (Z1).`
            : `MÉTODO POLARIZADO (Seiler): 80% vol Z1 puro, 20% en Z4-Z5. Máx 2 sesiones calidad/sem, nunca consecutivas.`;
    // ── Runner profile block ─────────────────────────────────────
    const expLabel = experienceLevel === 'beginner' ? 'Principiante (<1 año)' :
        experienceLevel === 'intermediate' ? 'Intermedio (1-3 años)' :
            experienceLevel === 'advanced' ? 'Avanzado (3+ años)' : 'Élite/Sub-élite';
    const terrainLabel = raceTerrain === 'road' ? 'asfalto/ciudad' :
        raceTerrain === 'trail' ? 'trail/montaña (incluir subidas, técnica)' :
            raceTerrain === 'mixed' ? 'mixto asfalto+trail' : 'pista atletismo';
    const priorityLabel = racePriority === 'A' ? 'Carrera A — objetivo principal, taper completo' :
        racePriority === 'B' ? 'Carrera B — objetivo secundario, taper parcial 3-4 días' :
            'Carrera C — entrenamiento con dorsales, sin taper';
    const injuryBlock = (() => {
        const parts = [];
        if (hasRecentInjury)
            parts.push(`LESIÓN RECIENTE: "${recentInjuryDetail || 'sí, sin detalles'}" — carga inicial conservadora, sin series hasta semana 2`);
        const areas = injuryAreas.filter(a => a !== 'Sin lesiones conocidas');
        if (areas.length > 0)
            parts.push(`Zonas crónicas: ${areas.join(', ')} — incluir ejercicios preventivos específicos y evitar sobrecargar esas zonas`);
        return parts.length > 0 ? parts.join('\n  ') : 'Sin lesiones ni limitaciones';
    })();
    const runnerProfileBlock = `PERFIL DEL CORREDOR:
  • Nivel: ${expLabel}
  • Edad: ${ageRange} años
  • Volumen actual: ~${currentWeeklyKm} km/semana
  • Rodaje largo reciente: ~${longestRecentRunKm} km
  • Tiempo máximo/sesión: ${maxSessionMinutes} min — NO superar este límite en ninguna sesión
  • Momento preferido: ${preferredTime === 'morning' ? 'mañana' : preferredTime === 'afternoon' ? 'tarde' : preferredTime === 'evening' ? 'noche' : 'flexible'}
  • Terreno objetivo: ${terrainLabel}
  • Prioridad carrera: ${priorityLabel}
  • Lesiones: ${injuryBlock}`;
    // ── Progression constraints derived from profile ────────────
    const maxInitialLongRunKm = Math.min(longestRecentRunKm + 2, longestRecentRunKm * 1.1);
    const maxWeeklyKmFirstWeek = Math.round(currentWeeklyKm * (experienceLevel === 'beginner' ? 0.85 : 1.0));
    const maxSessionNote = `Ninguna sesión supere ${maxSessionMinutes} minutos — ritmo de rodaje ajustado a este límite.`;
    const DAY_NAMES_ES = ['dom', 'lun', 'mar', 'mié', 'jue', 'vie', 'sáb'];
    const strengthNote = includeStrength
        ? strengthDaysOfWeek && strengthDaysOfWeek.length > 0
            ? `Fuerza FIJA los: ${strengthDaysOfWeek.map(d => DAY_NAMES_ES[d]).join(', ')} — NO poner fuerza en otros días.`
            : `Fuerza: ${strengthDaysCount} sesión/es semana (días libres).`
        : 'Sin fuerza.';
    const scheduleHint = (0, planHelpers_1.buildDayScheduleHint)(startISO, mesoEndISO, runDaysOfWeek && runDaysOfWeek.length > 0 ? runDaysOfWeek : null, strengthDaysOfWeek && strengthDaysOfWeek.length > 0 ? strengthDaysOfWeek : null);
    const developerInstructions = `Eres un entrenador de running científico y especializado. Devuelve SOLO JSON válido, sin texto antes o después.

FORMATO:
{"plan":[{"date":"YYYY-MM-DD","description":"descripción ejecutable","explanation":{"type":"series|umbral|tempo|largo|suave|descanso|fuerza","purpose":"objetivo fisiológico","details":"instrucciones paso a paso","intensity":"zona/ritmo o null","phase":"base|desarrollo|especifico|taper"}}]}

PLAN COMPLETO (contexto): ${race.name} · ${distKm || '?'}km · ${raceISO} · ${totalWeeks} semanas totales
MESOCICLO A GENERAR: 1 de ${totalMesocycles} — SOLO desde ${startISO} hasta ${mesoEndISO} (${mesoLenWeeks} semanas)
${runDaysOfWeek && runDaysOfWeek.length > 0
        ? `Running FIJO los: ${runDaysOfWeek.map(d => DAY_NAMES_ES[d]).join(', ')}`
        : `Días running/sem: ${runDays}`} · ${strengthNote}
Objetivo corredor: ${goal} · Ritmo objetivo: ${targetPace || 'no definido'}
Marca previa: ${(lastRace === null || lastRace === void 0 ? void 0 : lastRace.distance_km) ? `${lastRace.distance_km}km en ${lastRace.time || '?'}` : 'no disponible'}

${runnerProfileBlock}

RESTRICCIONES DE CARGA INICIALES:
• Semana 1 máx ~${maxWeeklyKmFirstWeek} km totales (no superar volumen actual de golpe)
• Rodaje largo semana 1 máx ~${Math.round(maxInitialLongRunKm)} km
• ${maxSessionNote}
${hasRecentInjury ? '• LESIÓN RECIENTE: primera semana sin series ni calidad — solo rodajes suaves y fuerza preventiva' : ''}
${raceTerrain === 'trail' ? '• TRAIL: incluir al menos 1 sesión/semana con subidas o terreno técnico, rodajes de montaña en Z1' : ''}
${raceTerrain === 'track' ? '• PISTA: mayor énfasis en series de velocidad y trabajo a ritmo de carrera' : ''}
${racePriority === 'C' ? '• CARRERA C: no hay taper — última semana igual que las anteriores, sin reducción de carga' : ''}

${zonesBlock}

FASES DEL PLAN COMPLETO:
${phasesBlock}

${methodologyBlock}
${scheduleHint ? `
CALENDARIO OBLIGATORIO — sigue EXACTAMENTE esta estructura por fecha:
${scheduleHint}
Los días marcados RUNNING deben tener workout de carrera (suave, calidad o largo).
Los días marcados FUERZA deben tener sesión de fuerza running-specific.
Los días marcados Descanso deben ser descanso. NO cambies ningún día.` : ''}
REGLAS (incumplir invalida el plan):
1. Descarga cada 4ª semana (−25-30% volumen)
2. Máx ${peakLongRun} en rodaje largo
3. Sin sesiones calidad en días consecutivos (48h mínimo entre ellas)
4. Fase BASE: cero calidad, 100% Z1
5. Rodajes suaves SIEMPRE en Z1
6. Adaptar complejidad de las sesiones al nivel ${expLabel}
7. Respetar el tiempo máximo de sesión de ${maxSessionMinutes} min

Genera EXACTAMENTE las fechas de ${startISO} a ${mesoEndISO}. Nada más.`;
    const userPrompt = `Genera el mesociclo 1 (${startISO} → ${mesoEndISO}) del plan para ${race.name}.`;
    // ── OpenAI call ─────────────────────────────────────────────
    async function callResponsesAPI(activeModel) {
        var _a;
        const res = await fetch('https://api.openai.com/v1/responses', {
            method: 'POST',
            headers: { Authorization: `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
            body: JSON.stringify({
                model: activeModel,
                input: [
                    { role: 'developer', content: developerInstructions },
                    { role: 'user', content: userPrompt },
                ],
            }),
            signal: AbortSignal.timeout(90000),
        });
        const raw = await res.text();
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        let data = null;
        try {
            data = JSON.parse(raw);
        }
        catch ( /* keep raw */_b) { /* keep raw */ }
        if (!res.ok)
            throw new Error(((_a = data === null || data === void 0 ? void 0 : data.error) === null || _a === void 0 ? void 0 : _a.message) || `OpenAI error ${res.status}`);
        const outputs = [];
        if (Array.isArray(data === null || data === void 0 ? void 0 : data.output)) {
            for (const item of data.output) {
                if ((item === null || item === void 0 ? void 0 : item.content) && Array.isArray(item.content)) {
                    for (const c of item.content) {
                        if (c.type === 'output_text' && typeof c.text === 'string')
                            outputs.push(c.text);
                    }
                }
            }
        }
        const combined = outputs.join('\n').trim();
        if (!combined)
            throw new Error('Respuesta OpenAI vacía');
        return combined;
    }
    // Type classifier for fallback
    function classify(desc) {
        const d = desc.toLowerCase();
        if (d.includes('series') || d.includes('fartlek') || /\dx\d/.test(d) || /\d×\d/.test(d))
            return 'series';
        if (d.includes('umbral'))
            return 'umbral';
        if (d.includes('tempo'))
            return 'tempo';
        if (d.includes('largo'))
            return 'largo';
        if (d.includes('descanso') || d.includes('rest'))
            return 'descanso';
        if (d.includes('fuerza'))
            return 'fuerza';
        return 'suave';
    }
    // ── Try OpenAI, fall back to algorithmic ───────────────────
    let rawContent = null;
    let openAiError = null;
    let usedModel = null;
    const candidateModels = [model, 'gpt-4o-mini'];
    for (const m of candidateModels) {
        try {
            rawContent = await callResponsesAPI(m);
            usedModel = m;
            break;
        }
        catch (err) {
            openAiError = err.message;
        }
    }
    let parsedPlan = null;
    if (rawContent) {
        const first = rawContent.indexOf('{');
        const last = rawContent.lastIndexOf('}');
        if (first !== -1 && last !== -1 && last > first) {
            try {
                parsedPlan = JSON.parse(rawContent.slice(first, last + 1).trim());
            }
            catch ( /* ignore */_b) { /* ignore */ }
        }
    }
    // Validate AI respected specific day constraints; force fallback if not
    if ((parsedPlan === null || parsedPlan === void 0 ? void 0 : parsedPlan.plan) && Array.isArray(parsedPlan.plan)) {
        const aiOk = (0, planHelpers_1.validateDayCompliance)(parsedPlan.plan, runDaysOfWeek && runDaysOfWeek.length > 0 ? runDaysOfWeek : null, strengthDaysOfWeek && strengthDaysOfWeek.length > 0 ? strengthDaysOfWeek : null);
        if (!aiOk) {
            parsedPlan = null;
            usedModel = null;
        }
    }
    if (!parsedPlan || !parsedPlan.plan || !Array.isArray(parsedPlan.plan)) {
        parsedPlan = (0, planHelpers_1.buildFallbackMesocycle)({
            startISO,
            endISO: mesoEndISO,
            totalWeeks,
            mesocycleStartWeek: 1,
            phases,
            taperWeeks,
            runDays,
            runDaysOfWeek: runDaysOfWeek && runDaysOfWeek.length > 0 ? runDaysOfWeek : null,
            includeStrength,
            strengthDaysOfWeek: strengthDaysOfWeek !== null && strengthDaysOfWeek !== void 0 ? strengthDaysOfWeek : null,
            strengthDaysCount,
            distKm,
            methodology,
            zones,
        });
        if (!usedModel)
            usedModel = `fallback-${methodology}`;
    }
    // Overwrite strength sessions with our validated templates
    if (includeStrength) {
        parsedPlan.plan = (0, planHelpers_1.postProcessStrengthSessions)(parsedPlan.plan, startISO, 1, phases, taperWeeks, mesoLenWeeks, distKm);
    }
    // Validate + fill missing explanations
    parsedPlan.plan.forEach(d => {
        if (!/^\d{4}-\d{2}-\d{2}$/.test(d.date))
            throw new https_1.HttpsError('internal', `Fecha inválida: ${d.date}`);
        if (typeof d.description !== 'string')
            throw new https_1.HttpsError('internal', 'Descripción inválida');
        if (!d.explanation || typeof d.explanation !== 'object') {
            const type = classify(d.description);
            d.explanation = { type, purpose: 'Entrenamiento', details: d.description };
        }
    });
    return Object.assign(Object.assign({}, parsedPlan), { meta: {
            fallback: !rawContent || (usedModel === null || usedModel === void 0 ? void 0 : usedModel.startsWith('fallback')),
            openAiError,
            model: usedModel,
            methodology,
            zones,
            phases: phases.map(p => ({ name: p.name, startWeek: p.startWeek, endWeek: p.endWeek })),
            // Mesocycle metadata
            total_weeks: totalWeeks,
            mesocycle_number: 1,
            mesocycle_length_weeks: mesoLenWeeks,
            mesocycle_start_date: startISO,
            mesocycle_end_date: mesoEndISO,
            total_mesocycles: totalMesocycles,
        } });
});
//# sourceMappingURL=generatePlan.js.map